### ISSUE TITLE
Spark Exception when training engine

### ISSUE THREAD

**Issue by vking34** [actionml/harness-docker-compose#16]
My ```engine.json```:
```
{
    "engineId": "1",
    "engineFactory": "com.actionml.engines.ur.UREngine",
    "sparkConf": {
        "spark.serializer": "org.apache.spark.serializer.KryoSerializer",
        "spark.kryo.registrator": "org.apache.mahout.sparkbindings.io.MahoutKryoRegistrator",
        "spark.kryo.referenceTracking": "false",
        "spark.kryoserializer.buffer": "300m",
        "spark.executor.memory": "3g",
        "spark.driver.memory": "3g",
        "spark.es.index.auto.create": "true",
        "spark.es.nodes": "elasticsearch",
        "spark.es.nodes.wan.only": "true"
    },
    "algorithm": {
        "indicators": [{
            "name": "buy"
        }, {
            "name": "detail-page-view"
        }]
    }
}
```
After I created an engine and input data.
I run training command
```
hctl train 1
```

Then I got the following error:
```
harness          | 03:42:42.954 INFO  SparkContext      - Running Spark version 2.3.3
harness          | 03:42:43.377 WARN  NativeCodeLoader  - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
harness          | 03:42:43.514 ERROR SparkContext      - Error initializing SparkContext.
harness          | org.apache.spark.SparkException: A master URL must be set in your configuration
harness          |      at org.apache.spark.SparkContext.<init>(SparkContext.scala:367)
harness          |      at com.actionml.core.spark.SparkContextSupport$$anonfun$1.apply(SparkContextSupport.scala:132)
harness          |      at com.actionml.core.spark.SparkContextSupport$$anonfun$1.apply(SparkContextSupport.scala:119)
harness          |      at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
harness          |      at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
harness          |      at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
harness          |      at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
harness          |      at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
harness          |      at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
harness          |      at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
harness          | 03:42:43.523 ERROR Utils             - Uncaught exception in thread ForkJoinPool-2-worker-7
harness          | java.lang.NullPointerException: null
harness          |      at org.apache.spark.SparkContext.org$apache$spark$SparkContext$$postApplicationEnd(SparkContext.scala:2389)
harness          |      at org.apache.spark.SparkContext$$anonfun$stop$1.apply$mcV$sp(SparkContext.scala:1904)
harness          |      at org.apache.spark.util.Utils$.tryLogNonFatalError(Utils.scala:1361)
harness          |      at org.apache.spark.SparkContext.stop(SparkContext.scala:1903)
harness          |      at org.apache.spark.SparkContext.<init>(SparkContext.scala:579)
harness          |      at com.actionml.core.spark.SparkContextSupport$$anonfun$1.apply(SparkContextSupport.scala:132)
harness          |      at com.actionml.core.spark.SparkContextSupport$$anonfun$1.apply(SparkContextSupport.scala:119)
harness          |      at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
harness          |      at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
harness          |      at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
harness          |      at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
harness          |      at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
harness          |      at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
harness          |      at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
harness          | 03:42:43.526 INFO  SparkContext      - Successfully stopped SparkContext
harness          | 03:42:43.528 ERROR SparkContextSupport$ - Spark context can not be created for job JobDescription(44682fa7-a8e0-454d-9eca-7f0554f3068a,queued,Spark job,Some(Wed Jan 13 03:42:42 GMT 2021),None)
harness          | org.apache.spark.SparkException: A master URL must be set in your configuration
harness          |      at org.apache.spark.SparkContext.<init>(SparkContext.scala:367)
harness          |      at com.actionml.core.spark.SparkContextSupport$$anonfun$1.apply(SparkContextSupport.scala:132)
harness          |      at com.actionml.core.spark.SparkContextSupport$$anonfun$1.apply(SparkContextSupport.scala:119)
harness          |      at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
harness          |      at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
harness          |      at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
harness          |      at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
harness          |      at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
harness          |      at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
harness          |      at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
harness          | 03:42:43.536 INFO  JobManager$       - Job 44682fa7-a8e0-454d-9eca-7f0554f3068a marked as failed
```

This may be the master URL for Spark was not configured. How can I resolve this problem?
Thank you.

**Comment by qqmbr4k** [comment]
Hi @vking34 
You should add "master" field to sparkConf

https://actionml.com/docs/h_ur_config#default-ur-settings

**Comment by vking34** [comment]
Thank you for your answer.
May I ask one more question?
I do not have Spark yet.
Which version Spark do I need to add to the docker-compose file?

**Comment by qqmbr4k** [comment]
for small dataset (e.g. minimum viable product setup) you can use `local` spark (it's built in) and it's 2.3.3 (see `Running Spark version 2.3.3` in the log). Later you may need a standalone spark 2.3.3

**Comment by vking34** [comment]
@andreyshikov thank you. now it works.
